version: '3.3'
services:
  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mongodb
    ports:
      - '27017:27017'
    image: mongo
    networks:
      - festival-network
    hostname: mongo

  review-app:
    container_name: review-app
    image: review-app:latest
    build: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '9091:9091'
    networks:
      - festival-network
    environment:
      - DATABASE_HOST=host.docker.internal
      - SPRING.DATA.MONGODB.URI=mongodb://mongodb:27017

networks:
  festival-network: {}